### PR TITLE
test workflow with heterogeneous catalysis test vocabulary

### PR DESCRIPTION
**Pull request by schumannj**

### CODE REVIEW

**Comment by schumannj** [comment]
Am i not supposed to test this workflow with the file I would use for the main voc4cat repository? I get the error that 

`ID of IRI https://w3id.org/nfdi4cat/voc4cat_0000005 is not in allowed ID range(s) of actor "0000-0002-6242-2167" (from provenance). (type=value_error)
Error: Process completed with exit code 1.` 

So it doesnt even get to the concepts I have added new.

**Comment by dalito** [comment]
The standard way to contribute new terms or changes to voc4cat is creating a pull request in the [voc4cat](https://github.com/nfdi4cat/voc4cat) repository. We should probably make clearer where to do what. It's great that you test and show us where better guidelines are needed.

The playground here is more to test the full tool-chain, for example, you and a co-worker could go through the whole process of collaborative editing a new test-vocabulary. If you want to continue in this way, we have to add a name for your test-vocabulary and ID reservations in this repository as first step. The missing ID reservations have caused the pipeline to fail `IRI https://w3id.org/nfdi4cat/voc4cat_0000005 is not in allowed ID range(s) of actor "0000-0002-6242-2167"`. The vocabulary names and ID reservation of the playground are in the file https://github.com/nfdi4cat/voc4cat-playground/blob/main/idranges.toml.

**Comment by dalito** [comment]
Are you aware that you can update a PR by continuing to commit to the branch in your fork upon which the PR was based? The changes will then automatically update the linked PR. There is no need to create a new PR. So it would have been sufficient to update the branch on which #4 was based with a new commit. It does no harm to create new PRs but updating the same PR is a much simpler workflow.

@nmoust This is something for the next version of the guidelines. We should suggested a proven series of commands (and screenshots).

**Comment by schumannj** [comment]
Thanks, now I see. That makes sense. In this case I will close this PR and and open a new one in the right repository at a later stage.

**Pull request closed without merging**
