### PR TITLE
Re-Submission of the Demo Biocatalysis Vocabulary

### PR DESCRIPTION
**Pull request by markdoerr**

### CODE REVIEW

**Comment by dalito** [comment]
The version number of the Excel template marks the structure (not formatting). It has to stay at "0.4.3".

The version is stored in sheet "Introduction", cell J11.

**Comment by markdoerr** [comment]
Hi @dalito,
I am puzzled - I thought, I used the current template from your template directory ...
anyway, I will change the version and re-submit ...

**Comment by dalito** [comment]
I vaguely remember that you proposed some changes to the template in December and therefore increased the version number. Maybe that is how 0.4.4 got in.

**Comment by markdoerr** [comment]
yes, true, @dalito ,
but for this test, I re-wrote the demo in the recent template provided by the repo ...
anyway, I made a new one and submitted it...

**Comment by markdoerr** [comment]
@dalito,
there is some issue with the URI parsing:

```   c = models.Concept(**concept_data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1100, in pydantic.main.validate_model
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/models.py", line 102, in check_uri_vs_config
    iri, *_fragment = values["uri"].split("#", 1)
```

**Comment by dalito** [comment]
There are some small issues:
- In prefix sheet the namespace "v4c-bc" has to be defined (-> https://github.com/nfdi4cat/voc4cat-tool/issues/205)
- ORCIDs were partly wrong because excel was counting up 0000 -> 0001 -> 0002 in a drag operation
- in concept scheme the IRI written as CURIE must have a ":" at the end to be recognized as CURIE

Please find attached the fixed xlsx: [biocatalysis_demo.xlsx](https://github.com/nfdi4cat/voc4cat-playground/files/14359192/biocatalysis_demo.xlsx)

**Comment by markdoerr** [comment]
Hi @dalito, 
where is this URI  https://example.org/voc4cat_biocatalysis/ in the pipeline error message coming from ?

**Comment by dalito** [comment]
In the pipeline we validate the URIs used against what is configured in `IDrange.toml` (in upstream main) to detect if someone changed the URIs, The config has

```toml
[vocabs.biocatalysis_demo]
id_length = 7
permanent_iri_part = "https://example.org/voc4cat_biocatalysis/"
```

You can either change the prefix definition (in prefix sheet) to point to `https://example.org/voc4cat_biocatalysis/` or I can change `IDrange.toml` to `w3id.org` if you prefer that.

**Comment by markdoerr** [comment]
I see, @dalito , :)
If you do not mind, please change it in the idrange.toml - the w3c IRI looks more realistic...

**Comment by dalito** [comment]
Done. 

I saw that in the concept scheme sheet you have `https://w3id.org/nfdi4cat/voc4cat_biocat:` (with colon at the end). For full URIs a colon at the end is not required (I expect another validation error). Only CURIES need a colon `v4c-bc:` to be recognized correctly.

**Comment by markdoerr** [comment]
I see, I will fix it an re-submit ...

**Comment by markdoerr** [comment]
Hi @dalito ,
... I think, Fort Knox is easier to enter ... ;)
do you quickly see, what is going wrong now ?

**Comment by dalito** [comment]
In concept scheme sheet add `https://w3id.org/nfdi4cat/voc4cat_biocat/` as Vocabulary IRI. (this cell may not be empty)

**Comment by markdoerr** [comment]
sorry, this was a bug of OpenOffice - it somehow dropped my corrections ...

**Comment by dalito** [comment]
The vocabulary parsing & conversion went fine now! 

Only the last step the auto-update of the PR-branch failed, which wants to make a commit that removes xlsx and adds ttl-files. I wonder if `remote: Permission to LARAontologies/voc4cat-playground.git denied to github-actions[bot].` has to do with the missing right "Allow edits by maintainers" on this PR. 

In https://github.com/nfdi4cat/voc4cat/pull/55 it worked fine a few hours ago but there "Allow edits by maintainers" was activated. 

If this proofs correct we need to point out to keep "Allow edits by maintainers" activated when submitting a PR.

Just to be sure that this is the real reason: Did you change anything in the repository settings of your fork? Reduced action permissions or additional branch protection rules could also cause also the commit failure.

**Comment by dalito** [comment]
I think it is not possible to set "Allow edits by maintainers" after PR creation or do you see such option as the PR author?

If you can't change it, can you maybe submit a new PR just with the last version of the xlsx file and activate "Allow edits by maintainers" in the new PR?

**Comment by markdoerr** [comment]
@dalito , no I do not see a button to allow edits by the maintainer. 

I will make a new PR.

**Comment by dalito** [comment]
@markdoerr I just added shell scripts for unix ([test_xlsx_locally.sh](https://github.com/nfdi4cat/voc4cat-playground/blob/main/test_xlsx_locally.sh)) and windows ([test_xlsx_locally.bat](https://github.com/nfdi4cat/voc4cat-playground/blob/main/test_xlsx_locally.bat)) to locally test a vocabulary xlsx-file in the `inbox-excel-vocabs`-folder and the `IDrange.toml`-file in the same way as in CI. 
Maybe such script is useful in the future but understanding the exact reason of an error may not always be so straight-forward.

**Comment by markdoerr** [comment]
:+1:  Very good, @dalito ,
I was about to ask you, if there is something like a pre-check  .... 
I had to teach the whole day, so I will briefly re-submit tonight.

**Pull request closed without merging**
