### PR TITLE
Biocatalysis Demo Vocabulary for pipeline testing

### PR DESCRIPTION
**Pull request by markdoerr**
Biocatalysis Vocabulary v1.1

### CODE REVIEW

**Comment by markdoerr** [comment]
Hi @dalito,
there is an issue in the pipeline:

`Run voc4cat --version
  
voc4cat 0.7.8
INFO    |Executing cmd: voc4cat check --config _main_branch/idranges.toml --logfile outbox/voc4cat.log --ci-pre inbox-excel-vocabs/ _main_branch/vocabularies
DEBUG   |Processing common options.
DEBUG   |Config loaded from: _main_branch/idranges.toml
ERROR   |Unexpected error.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 450, in run_cli_app
    main_cli(raw_args)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 441, in main_cli
    process_common_options(args, raw_args)
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 47, in process_common_options
    config.load_config(config_file=Path(args.config))
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/site-packages/voc4cat/config.py", line 144, in load_config
    new_conf["IDRANGES"] = IDrangeConfig(**conf)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line [34](https://github.com/nfdi4cat/voc4cat-playground/actions/runs/7192810528/job/19589991308?pr=2#step:7:35)1, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for IDrangeConfig
vocabs -> biocatalysis_demo -> id_range -> 0 -> orcid
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)
vocabs -> biocatalysis_demo -> id_range -> 0 -> ror_id
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)
Error: Process completed with exit code 3.`

**Comment by dalito** [comment]
I somewhat expected some failures. I don't have time to look now. The main difference between here and the voc4cat repo is that voc4cat is constrained to one vocab per repo whereas here you can have multiple vocab in the same repo. This has not been tested much.

**Comment by dalito** [comment]
The reason for the failure is that the ORCID and ROR in the config `idrange.toml` are invalid (from #1). For ORCID a checksum is calculated and your fantasy ORCID had an incorrect checksum. The error in the pipeline points to it somewhat
```
pydantic.error_wrappers.ValidationError: 2 validation errors for IDrangeConfig
vocabs -> biocatalysis_demo -> id_range -> 0 -> orcid
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)
vocabs -> biocatalysis_demo -> id_range -> 0 -> ror_id
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)
```
It would be nice if the custom validators for ORCID & ROR would give more meaningful error messages. However, I don't plan to add features to current pydantic 1 code. For pydantic 2 the custom validation has to be rewritten (https://github.com/nfdi4cat/voc4cat-tool/issues/142).

The easiest fix is to replace ORCID and ROR with an empty string (or with valid values). I did this in #3.

**Comment by dalito** [comment]
@markdoerr - Rerunning the job gave another error. This one is for you. :)

**Comment by markdoerr** [comment]
Thanks, @dalito,
I will have a look (but unfortunately the whole day is filled today), so it might take until tomorrow :(

**Pull request closed without merging**
