### PR TITLE
Re-submission of demo biocat vocabulary

### PR DESCRIPTION
**Pull request by markdoerr**
re-submission after fixing the id_ranges.toml file

### CODE REVIEW

**Comment by markdoerr** [comment]
... now it progressed a little bit further:
it looks, like there is an argument too much ....

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 450, in run_cli_app
    main_cli(raw_args)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 441, in main_cli
    process_common_options(args, raw_args)
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/cli.py", line 47, in process_common_options
    config.load_config(config_file=Path(args.config))
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/voc4cat/config.py", line 142, in load_config
    new_conf["IDRANGES"] = IDrangeConfig(**conf)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for IDrangeConfig
vocabs -> biocatalysis_demo -> id_range -> 0 -> ror_id
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)
Error: Process completed with exit code 3.
```

**Comment by dalito** [comment]
Sorry. ~~The multi-vocabulary use is still a rough path. The error is related to parsing of the multi-vocabulary config file.~~ I was able to reproduce it locally and will have a look.

Update: The error was rather trivial, see next message.

**Comment by dalito** [comment]
@markdoerr - The message is a validation error from pydantic but difficult to understand: The problem is that ROR-Ids have to start with `https://ror.org/` (in contrast ORCID where the domain its optional).

In `IDrange.toml` you have to change the line `ror_id = "00r1edq15"` to `ror_id = "https://ror.org/00r1edq15"`.

**Comment by markdoerr** [comment]
A, thanks, @dalito ,
I suspected something like this ... maybe it should be stated as a comment, in what format the IDs are required ...

**Comment by dalito** [comment]
I made the fix in IDrange.toml in main as well and restarted the pipeline. Finally its green!

**Comment by dalito** [comment]
If you plan to submit the vocabulary in #2, you can close this one. Since I fixed main directly there would be nothing left here after resolving conflicts. IDranges.toml in main now has:
```toml
[[vocabs.biocatalysis_demo.id_range]]
first_id = 1
last_id = 300
gh_name = "markdoerr"
orcid =   "0000-0003-3270-6895"
ror_id = "https://ror.org/00r1edq15"
```

**Comment by markdoerr** [comment]
Hi @dalito,
I think we changed the same file simultaneously.
Could you please quickly resolve the issue. 
Then I would finally try to submit the demo vocabulary and we will see... thanks

**Comment by dalito** [comment]
Which issue exactly? I think you need to resolve the conflict in the standard git way locally and rebase the PR-branch on current head of origin/master. (either here or in the branch used in #2)

...or shoud I push an update to this branch?

**Comment by markdoerr** [comment]
@dalito ,
the fastest way with githbub to resolve the conflict is, if you simply click on the "resolve conflicts" button below and accept the change :) - I am not allowed to press the accept button.

**Comment by dalito** [comment]
It looks like I am not allowed to push. Here is what I did:

````
> git clone https://github.com/LARAontologies/voc4cat-playground.git
Cloning into 'voc4cat-playground'...
> cd voc4cat-playground\
> git switch feature/biocat-vocab
Switched to a new branch 'feature/biocat-vocab'
> git remote add upstream https://github.com/nfdi4cat/voc4cat-playground
> git pull upstream main
...
Auto-merging idranges.toml
CONFLICT (content): Merge conflict in idranges.toml
Automatic merge failed; fix conflicts and then commit the result.

< fixed conflicts >

λ git status
...
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:
        modified:   idranges.toml

> git commit -m "Merged updates form upstream/main"
> git push
remote: Permission to LARAontologies/voc4cat-playground.git denied to dalito.
```

**Comment by dalito** [comment]
I don't have a resolve conflict button. I just see the warning "This branch has conflicts that must be resolved" without any link or button. Did you "allow edits by maintainers" on the PR?

**Comment by dalito** [comment]
Ah. Now I can merge. Should I?

**Comment by markdoerr** [comment]
@dalito , interesting, that the button was only shown to me.
Yes, please merge now. Thanks.

**Pull request merged**
